#manifest
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-cv-deployment
spec:
  selector:
    matchLabels:
      app: httpd-cv-server
  replicas: 1
  template:
    metadata:
      labels:
        app: httpd-cv-server
    spec:
      containers:
        - name: httpd-cv-container
          #image: gcr.io/tensorflow-serving/resnet
          image: docker.io/joseemanuel/angularcv:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: httpd-cv-service
  name: httpd-cv-service
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: httpd-cv-server
  type: LoadBalancer
